# create 语句
create_table: "create table user (
  id int,
  name varchar(20),
  type varchar(20),
  age int,
  mobile varchar(20),
  )"

# 枚举描述
enums_definition:
  status:
    - key: normal
      value: 1
      desc: normal user
    - key: vip
      value: 2
      desc: vip user
    - key: admin
      value: 3
      zh: 管理员
      desc: admin user

# 字段定义 描述
table_definition:
  user:
    - column_name: id
    - column_name: age
    - column_name: name
    - column_name: type
      oneof:
        enums: status
        select: [normal, vip, admin] # 如果为空选中全部
    - column_name: mobile
      fromat: mobile

message_definition:
  id:
    - column_name: id
      array: true
      inhibit: required

api_definition:
  oss: # 方法组名称
    - name: get
      http:
        method: get
        path: v1/oss/get
        summary: "get"
        body: "*"
      request: api.oss.oss.get_request
      response: api.oss.oss.get_response

